name: CI

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Yarn
        uses: ./.github/actions/setup-yarn
        with:
          node-version: "22"
          immutable: "true"
      - name: Run tests and coverage
        run: yarn coverage || yarn run coverage
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
