name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Yarn
        uses: ./.github/actions/setup-yarn
        with:
          node-version: "22"
          immutable: "true"

      - name: Build
        run: yarn build

      - name: Upload build artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
